version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: bot.dockerfile
      args:
          environment_type: ${ENVIRONMENT_TYPE}
    volumes:
      - ./electora_bot:/app/electora_bot
