apiVersion: v1
kind: Pod
metadata:
  name: electora-bot
  namespace: default
spec:
  containers:
    - name: electora-bot
      image: ghcr.io/electora-vote/electora-bot:latest
      command:
        - bash
        - -c
        - /venv/bin/python -m electora_bot
      env:
        - name: COMMAND_PREFIX
          value: "!"
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: electora-discord-bot
              key: discord-token
  restartPolicy: Always
